# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
---
extends: default

rules:
  # 80 chars should be enough, but don't fail if a line is longer
  line-length:
    max: 100
    level: warning
