
source $HOME/dotfiles/vim/general.vimrc
source $HOME/dotfiles/vim/plugins.vimrc
source $HOME/dotfiles/vim/plugin_config.vimrc
source $HOME/dotfiles/vim/keys.vimrc
source $HOME/dotfiles/vim/theme.vimrc
source $HOME/dotfiles/vim/other.vimrc
