bare_repository_elements=("branches"  "config"  "description"  "HEAD"  "hooks"  "info"  "objects"  "refs")
dotfiles=(".vimrc" ".bashrc" ".gitconfig" ".tmux.conf")
github_repository_ssh_url="git@github.com:stanleyuan/dotfiles.git"
github_repository_https_url="https://github.com/stanleyuan/dotfiles.git"
bare_repository=".dotfiles"
config_keyword="config"
config_keyword=config
config_keyword=config
config_keyword=config
config_keyword=config
config_keyword=config
config_keyword=config
