---
# At sundown, it will look for scripts in $XDG_DATA_DIRS/dark-mode.d/.
# At sunrise, it will look for scripts in $XDG_DATA_DIRS/light-mode.d/.
# https://gitlab.com/WhyNotHugo/darkman/-/tree/main?ref_type=heads
#
# If $XDG_DATA_DIRS is either not set or empty
# a value equal to /usr/local/share/:/usr/share/ should be used.
# https://specifications.freedesktop.org/basedir-spec/latest/
#
# $ sudo ln -s ~/dotfiles/misc/darkman/dark-mode.d /usr/local/share
# $ sudo ln -s ~/dotfiles/misc/darkman/light-mode.d /usr/local/share
lat: 53.3498  # Replace with your latitude
lng: -0.1  # Replace with your longitude
# usegeoclue: true  # Set to true if you want automatic location detection
dbusserver: true
portals: true
