-- require("schema-companion").setup({
--   formatting = true,
--   log_level = "info",
--   -- if you have telescope you can register the extension
--   enable_telescope = true,
--   matchers = {
--     -- add your matchers
--     require("schema-companion.matchers.kubernetes").setup({ version = "master" }),
--   },
--   schemas = {
--     {
--       name = "Kubernetes master",
--       uri = "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/all.json",
--     },
--     {
--       name = "Kubernetes v1.29",
--       uri = "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.29.3-standalone-strict/all.json",
--     },
--     {
--       name = "Kubernetes v1.30",
--       uri = "https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.3-standalone-strict/all.json",
--     },
--     {
--       name = "Protolint",
--       uri = "~/.config/nvim/schemas/protolint.json",
--     },
--   },
-- })
